//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CountryInfo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string CountryCode { get; set; }
        public int Capital { get; set; }
        public decimal Square { get; set; }
        public int Population { get; set; }
        public int RegionId { get; set; }
    
        public virtual City City { get; set; }
        public virtual Region Region { get; set; }
    }
}
